# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true

[footer]
since = 2023
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "🛠️"
subtitle = "My dev/infosec blog, enjoy reading!"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[article]
math = false
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

# Not setup
[opengraph.twitter]
site = ""
card = "summary_large_image"

# Not setup
[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

# ## Comments
# [comments]
# enabled = true
# provider = "disqus"

# # Not setup
# [comments.disqusjs]
# shortname = ""
# apiUrl = ""
# apiKey = ""
# admin = ""
# adminLabel = ""

# # Not setup
# [comments.utterances]
# repo = ""
# issueTerm = "pathname"
# label = ""

# # Not setup
# [comments.remark42]
# host = ""
# site = ""
# locale = ""

# # Not setup
# [comments.vssue]
# platform = ""
# owner = ""
# repo = ""
# clientId = ""
# clientSecret = ""
# autoCreateIssue = false

# # Not setup
# [comments.waline]
# serverURL = ""
# lang = ""
# visitor = ""
# avatar = ""
# emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
# requiredMeta = ["name", "email", "url"]
# placeholder = ""

# # Not setup
# [comments.waline.locale]
# admin = "Admin"

# # Not setup
# [comments.twikoo]
# envId = ""
# region = ""
# path = ""
# lang = ""

# # Not setup
# [comments.cactus]
# defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
# serverName = "cactus.chat"
# siteName = ""

# # Not setup
# [comments.giscus]
# repo = ""
# repoID = ""
# category = ""
# categoryID = ""
# mapping = ""
# lightTheme = ""
# darkTheme = ""
# reactionsEnabled = 1
# emitMetadata = 0

# # Not setup
# [comments.gitalk]
# owner = ""
# admin = ""
# repo = ""
# clientID = ""
# clientSecret = ""

# # Not setup
# [comments.cusdis]
# host = ""
# id = ""
